### ISSUE TITLE
Link to ARM compiler -> 404

### ISSUE THREAD

**Issue by MortenGuldager** [onethinx/VSCodeHelloWorld#1]
The link to a ARM download in Readme_SetupVScode.md returns 404

**Comment by RolfNoot** [comment]
It points to [https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads)

For me it doesn't return a 404.

**Comment by MortenGuldager** [comment]
yeah, see it works now. I must have caught Arm in the middle of the stream.
